import { AppState, AppStateError } from './app.state';

// export const appStore = new AppState();

export const appStore: AppState = {
    factAllData: null,
    factAll: null,
    grafData: null,
    catalogData: null,
    factFilterData: null,
    catalogDataSearch: null,
    yearFilterData: null,
    academicFilterData: null,
    anafGlobalFilterData: null,
    ganderFilterData: null,
    gilFilterData: null,
    godelFilterData: null,
    leomFilterData: null,
    mddFilterData:null,
    sektorFilterData:null,
    anafFilterData:null,
    givunGroupFilterData:null,
    selectgil: null,
    selectgodel: null,
    selectleom: null,
    selectanafGlobal: null,
    selectanaf: null,
    selectacademic: null,
    selectgander: null,
    selectsektor: null, 
    selectgivunGroup: null,
    selectyear: null,
    selectmdd: null,
    filterStr: null,
    BoUrl: null,
    tags: null,
    grafData2: null,
    grafData3: null,
    grafData4: null,
    grafData5: null,
    grafData6: null,
    pieChartNoAcademi1: null,
    pieChartNoAcademi2: null,
    pieChartNoAcademi3: null,
    pieChartNoAcademi4: null,
    pieChartNoAcademi5: null,
    pieChartAcademi1: null,
    pieChartAcademi2: null,
    pieChartAcademi3: null,
    pieChartAcademi4: null,
    pieChartAcademi5: null,
    homePageData: null,
    homePageSumData: null,
    homePageSumAllData: null,
    disableGander: null,
    disableGil: null,
    isReady: null,
    academicPrcnt: null,
    givunGroupData0: null,
    givunGroupData1: null,
    givunGroupData2: null,
    givunGroupData3: null,
    countEmpSum: null,
    countEmpSumData: null,
    tokenCaptcha: null,

};

export const APP_STORE_PROVIDER = {provide: AppState, useValue: appStore};
